// Generated for MicroPython 1.16
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (16)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_RELEASE_LEVEL (MICROPY_RELEASE_LEVEL_FINAL)
#define MICROPY_VERSION_STRING "1.16.0"
